name: green-roofs
channels:
- ioam
- conda-forge
- defaults
dependencies:
- affine=2.1.0=py35_0
- alabaster=0.7.10=py35_0
- anaconda-client=1.6.3=py35_0
- anaconda-project=0.7.1=py35_0
- asn1crypto=0.22.0=py35_0
- astroid=1.5.3=py35_0
- astropy=2.0.1=np113py35_1
- attrs=17.2.0=py35_0
- babel=2.4.0=py35_0
- beautifulsoup4=4.6.0=py35_0
- biggus=0.15.0=py35_0
- bitarray=0.8.1=py35_0
- bkcharts=0.2=py35_0
- blas=1.1=openblas
- blaze=0.11.3=py35_0
- bleach=1.5.0=py35_0
- bokeh=0.12.6=py35_0
- boost=1.64.0=py35_4
- boost-cpp=1.64.0=1
- boto3=1.4.4=py35_0
- botocore=1.5.92=py35_0
- bottleneck=1.2.1=np113py35_0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- cairo=1.14.6=4
- cartopy=0.15.1=np113py35_2
- certifi=2017.7.27.1=py35_0
- cf_units=1.1.3=py35_1
- cffi=1.10.0=py35_0
- chardet=3.0.4=py35_0
- click=6.7=py35_0
- click-plugins=1.0.3=py35_0
- cligj=0.4.0=py35_0
- cloudpickle=0.4.0=py35_0
- clyent=1.2.2=py35_0
- colorama=0.3.9=py35_0
- contextlib2=0.5.5=py35_0
- cryptography=1.9=py35_0
- curl=7.52.1=0
- cycler=0.10.0=py35_0
- cython=0.26=py35_0
- cytoolz=0.8.2=py35_0
- dask=0.15.1=py35_0
- datashape=0.5.4=py35_0
- decorator=4.1.2=py35_0
- descartes=1.1.0=py35_0
- distributed=1.18.0=py35_0
- docutils=0.14=py35_0
- entrypoints=0.2.3=py35_1
- et_xmlfile=1.0.1=py35_0
- expat=2.1.0=3
- fastcache=1.0.2=py35_0
- fiona=1.7.9=py35_0
- flask=0.12.2=py35_0
- flask-cors=3.0.3=py35_0
- fontconfig=2.12.1=4
- freetype=2.7=1
- freexl=1.0.2=2
- gdal=2.1.4=py35_1
- geopandas=0.2.1=py35_4
- geos=3.5.1=1
- gevent=1.2.2=py35_0
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- gmpy2=2.0.8=py35_1
- greenlet=0.4.12=py35_0
- h5netcdf=0.3.1=py35_0
- h5py=2.7.0=np113py35_1
- hdf4=4.2.12=0
- hdf5=1.8.18=1
- heapdict=1.0.0=py35_0
- holoviews=1.8.2=py35_0
- html5lib=0.9999999=py35_0
- hypothesis=3.17.0=py35_0
- icu=58.1=1
- idna=2.5=py35_0
- imageio=2.2.0=py35_0
- imagesize=0.7.1=py35_0
- ipykernel=4.6.1=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=7.0.0=py35_0
- iris=1.13.0=py35_1
- isort=4.2.15=py35_0
- itsdangerous=0.24=py35_1
- jbig=2.1=0
- jdcal=1.3=py35_0
- jedi=0.10.2=py35_0
- jinja2=2.9.6=py35_0
- jmespath=0.9.3=py35_0
- jpeg=9b=0
- json-c=0.12.1=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- kealib=1.4.7=2
- lancet=0.9.0=py35_0
- lazy-object-proxy=1.3.1=py35_0
- libdap4=3.18.3=2
- libffi=3.2.1=3
- libgdal=2.1.4=2
- libiconv=1.14=4
- libkml=1.3.0=1
- libmo_unpack=3.0=1
- libnetcdf=4.4.1.1=6
- libpng=1.6.28=1
- libpq=9.6.3=0
- libsodium=1.0.10=0
- libspatialindex=1.8.5=1
- libspatialite=4.3.0a=15
- libtiff=4.0.6=7
- libxml2=2.9.4=4
- libxslt=1.1.29=5
- locket=0.2.0=py35_1
- lxml=3.8.0=py35_0
- markupsafe=1.0=py35_0
- matplotlib=2.0.2=py35_2
- mccabe=0.6.1=py35_0
- mistune=0.7.4=py35_0
- mo_pack=0.2.0=py35_1
- mpc=1.0.3=4
- mpfr=3.1.5=0
- mpmath=0.19=py35_2
- msgpack-python=0.4.8=py35_0
- multipledispatch=0.4.9=py35_0
- munch=2.2.0=py35_0
- nbconvert=5.2.1=py35_1
- nbformat=4.3.0=py35_0
- nc_time_axis=1.0.2=py35_0
- ncurses=5.9=10
- netcdf4=1.2.9=py35_1
- networkx=1.11=py35_0
- nltk=3.2.4=py35_0
- nose=1.3.7=py35_2
- notebook=5.0.0=py35_0
- numexpr=2.6.2=np113py35_0
- numpy=1.13.1=py35_blas_openblas_200
- numpydoc=0.7.0=py35_0
- odo=0.5.1=py35_0
- olefile=0.44=py35_0
- openblas=0.2.19=2
- openjpeg=2.1.2=2
- openpyxl=2.5.0a2=py35_0
- openssl=1.0.2l=0
- owslib=0.14.0=py35_1
- packaging=16.8=py35_0
- pandas=0.20.3=py35_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py35_0
- param=1.5.1=py35_0
- partd=0.3.8=py35_0
- path.py=10.3.1=py35_0
- pathlib2=2.3.0=py35_0
- patsy=0.4.1=py35_0
- pcre=8.39=0
- pep8=1.7.0=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.2.1=py35_1
- pip=9.0.1=py35_0
- pixman=0.34.0=0
- ply=3.10=py35_0
- poppler=0.52.0=2
- poppler-data=0.4.7=0
- proj4=4.9.3=4
- prompt_toolkit=1.0.15=py35_0
- psutil=5.2.2=py35_0
- psycopg2=2.7.3=py35_0
- ptyprocess=0.5.2=py35_0
- py=1.4.34=py35_0
- pycodestyle=2.3.1=py35_0
- pycosat=0.6.2=py35_0
- pycparser=2.18=py35_0
- pycrypto=2.6.1=py35_1
- pyepsg=0.3.2=py35_0
- pyflakes=1.6.0=py35_0
- pygments=2.2.0=py35_0
- pyke=1.1.1=py35_0
- pylint=1.7.1=py35_0
- pympler=0.5=py35_0
- pyodbc=4.0.17=py35_0
- pyopenssl=17.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pyproj=1.9.5.1=py35_0
- pyqt=5.6.0=py35_4
- pysal=1.13.0=py35_0
- pyshp=1.2.11=py35_0
- pysocks=1.6.7=py35_0
- pytables=3.4.2=np113py35_1
- pytest=3.2.1=py35_0
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- pywavelets=0.5.2=np113py35_0
- pyyaml=3.12=py35_1
- pyzmq=16.0.2=py35_2
- qtawesome=0.4.4=py35_0
- qtconsole=4.3.1=py35_0
- qtpy=1.3.1=py35_0
- rasterio=0.36.0=py35_0
- readline=6.2=0
- requests=2.18.4=py35_1
- rope=0.10.5=py35_0
- rtree=0.8.3=py35_0
- ruamel_yaml=0.11.14=py35_0
- s3transfer=0.1.10=py35_1
- scikit-image=0.13.0=py35_1
- scikit-learn=0.19.0=py35_blas_openblas_201
- scipy=0.19.1=py35_blas_openblas_202
- seaborn=0.8.0=py35_0
- setuptools=36.2.2=py35_0
- shapely=1.5.17=py35_4
- simplegeneric=0.8.1=py35_0
- singledispatch=3.4.0.3=py35_0
- sip=4.18=py35_1
- six=1.10.0=py35_1
- snowballstemmer=1.2.1=py35_0
- snuggs=1.4.1=py35_0
- sortedcollections=0.5.3=py35_0
- sortedcontainers=1.5.7=py35_0
- sphinx=1.6.3=py35_0
- sphinxcontrib-websupport=1.0.1=py35_0
- spyder=3.2.1=py35_0
- sqlalchemy=1.1.13=py35_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=np113py35_0
- sympy=1.1.1=py35_0
- tblib=1.3.2=py35_0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- toolz=0.8.2=py35_0
- tornado=4.5.1=py35_0
- traitlets=4.3.2=py35_0
- typing=3.6.2=py35_0
- udunits2=2.2.23=0
- unicodecsv=0.14.1=py35_0
- unixodbc=2.3.4=1
- urllib3=1.22=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=3.0.2=py35_0
- wrapt=1.10.11=py35_0
- xarray=0.9.6=py35_0
- xerces-c=3.1.4=3
- xlrd=1.0.0=py35_1
- xlsxwriter=0.9.8=py35_0
- xlwt=1.2.0=py35_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zict=0.1.2=py35_0
- zlib=1.2.8=3
- _license=1.1=py35_1
- anaconda=custom=py35_0
- anaconda-navigator=1.6.4=py35_0
- backports=1.0=py35_0
- boto=2.48.0=py35_0
- get_terminal_size=1.0.0=py35_0
- llvmlite=0.19.0=py35_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py35_3
- navigator-updater=0.1.0=py35_0
- pycurl=7.43.0=py35_2
- zope=1.0=py35_0
- zope.interface=4.4.2=py35_0
- geoviews=1.3.2=py35_0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - brokenaxes==0.2
  - cf-units==1.1.3
  - et-xmlfile==1.0.1
  - geojson==2.0.0
  - geopy==1.11.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - lancet-ioam==0.9.0
  - mo-pack==0.2.0
  - nc-time-axis==1.0.2
  - prompt-toolkit==1.0.15
  - ruamel-yaml==0.11.14
  - tables==3.4.2
